### ISSUE TITLE
Virtual Machine or Container

### ISSUE THREAD

**Issue by moisesguimaraes** [cassiopc/boca#10]
Is there an initiative to have a Dockerfile or a Vagrantfile to easly provide a BOCA installation?

**Comment by cassiopc** [comment]
It would be nice, but currently no, not that I'm aware at least.

**Comment by moisesguimaraes** [comment]
Then could you provide the list of packages I would have to install on a clean Debian/Ubuntu/CentOS (please name the most popular for boca deployments) and point me to the best direction to create a reusable boca image for docker?

**Comment by alejolp** [comment]
@moisesguimaraes Boca has historically used Ubuntu. It should also work with Debian, but I haven't done it in a long time. Boca has recently migrated to Debian packages, which is the default for both Debian and Ubuntu package system. The installation instructions can be found at: http://bombonera.org/install2017.txt

Installing packages from the instructions should provide the required dependencies, but if you are curious you can always look at the debian/control file in this repository.

**Comment by moisesguimaraes** [comment]
awesome, thanks @alejolp!

**Comment by rlaiola** [comment]
@moisesguimaraes and @cassiopc you can find a dockerized version of BOCA in which we've been working at https://github.com/joaofazolo/boca-docker

It's been even modularized in microservices to support maintainability and scalability.

Cheers!
